global using System.ComponentModel.DataAnnotations.Schema;
global using static thinkbridge.Grp2BackendAN.Core.Enums.PaginationEnums;
global using System.Runtime.Serialization;
global using AutoMapper;
global using System.Reflection;
global using thinkbridge.Grp2BackendAN.Core.Common;
global using FluentValidation;
global using FluentValidation.AspNetCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using thinkbridge.Grp2BackendAN.Core.Common.Mapping;
global using System.Net;
global using thinkbridge.Grp2BackendAN.Core.Models;
global using thinkbridge.Grp2BackendAN.Core.Entities;
